### ISSUE TITLE
Need to update CI to new version

### ISSUE THREAD

**Issue by terrydphillips** [FirewallRobotics/2024-Zenith#9]
https://github.com/FirewallRobotics/2024-Zenith/blob/4e2da481071fd200309edfc88d70093131aa575a/.github/workflows/main.yml#L21C50-L21C50

2023-22.04 needs to be updated to 2024-22.04. 

For reference -  
https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html

**Comment by NoobinOut** [comment]
She did this 2 weeks ago and forgot to close :)
